### ISSUE TITLE
JMX authentication failed, with credentials supplied in config

### ISSUE THREAD

**Issue by spynode** [dimovelev/metrics-sampler#9]
I am building package manually, since I encounter same issue as #6 when using latest pre-built package (metrics-sampler-distribution-0.6.0-all.tar.gz)

With manually built metrics-sampler, same config file gets loaded and application starts properly. I am able to fetch metrics from JMX instances without authentication and send them to Graphite. 

Problem arises when fetching metrics from JMX which requires auth. 
This is how relevant configuration looks like:
```xml
<configuration>
	<shared-resources>
		<thread-pool name="samplers" size="10" />
	</shared-resources>
	<inputs>
		<jmx name="jmx-template" template="true" username="username" password="password" persistent-connection="true">
 			<ignore-object-names>
				<ignore-object-name regexp="^java.lang.*" />
			</ignore-object-names>
		</jmx>
 		<jmx name="host-a" url="service:jmx:rmi:///jndi/rmi://10.10.10.110:8099/jmxrmi" parent="jmx-template" />
        </inputs>
	<selector-groups>
		<selector-group name="simple">
			 <regexp from-name="(.*):name=(.*)" to-name="${input.name}.${name[1]}.${name[2]}" />
		</selector-group>
	</selector-groups>
	<outputs>
		<console name="console" />
		<graphite name="graphite" host="10.10.10.118" port="2003" />
	</outputs>
	<samplers>
 		<sampler input="host-a" outputs="graphite" interval="60">
 			<selectors>
 				<use-group name="simple" />
 			</selectors>
		</sampler>
	</samplers>
</configuration>
```
I have tried the same configuration without using templates.

This is exception:

2015-09-15 14:43:40,618 WARN  [host-a] o.m.resources.SamplerTask - Sampler threw exception. Ignoring.
java.lang.SecurityException: Authentication failed! Credentials required
        at com.sun.jmx.remote.security.JMXPluggableAuthenticator.authenticationFailure(JMXPluggableAuthenticator.java:211) ~[na:1.8.0_45]
        at com.sun.jmx.remote.security.JMXPluggableAuthenticator.authenticate(JMXPluggableAuthenticator.java:163) ~[na:1.8.0_45]
        at sun.management.jmxremote.ConnectorBootstrap$AccessFileCheckerAuthenticator.authenticate(ConnectorBootstrap.java:219) ~[na:1.8.0_45]
        at javax.management.remote.rmi.RMIServerImpl.doNewClient(RMIServerImpl.java:232) ~[na:1.8.0_45]
        at javax.management.remote.rmi.RMIServerImpl.newClient(RMIServerImpl.java:199) ~[na:1.8.0_45]
        at sun.reflect.GeneratedMethodAccessor247.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323) ~[na:1.8.0_45]
        at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[na:1.8.0_45]
        at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[na:1.8.0_45]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_45]
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[na:1.8.0_45]
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568) ~[na:1.8.0_45]
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826) ~[na:1.8.0_45]
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$94(TCPTransport.java:683) ~[na:1.8.0_45]
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$8/475924306.run(Unknown Source) ~[na:na]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_45]
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682) ~[na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276) ~[na:1.8.0_45]
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253) ~[na:1.8.0_45]
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162) ~[na:1.8.0_45]
        at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source) ~[na:1.8.0_45]
        at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2432) ~[na:1.8.0_45]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308) ~[na:1.8.0_45]
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[na:1.8.0_45]
        at org.metricssampler.extensions.jmx.JmxConnection.establishConnection(JmxConnection.java:63) ~[metrics-sampler-extension-jmx.jar:na]
        at org.metricssampler.extensions.jmx.JmxConnection.connect(JmxConnection.java:56) ~[metrics-sampler-extension-jmx.jar:na]
        at org.metricssampler.extensions.jmx.JmxMetricsReader.open(JmxMetricsReader.java:307) ~[metrics-sampler-extension-jmx.jar:na]
        at org.metricssampler.extensions.base.DefaultSampler.readMetrics(DefaultSampler.java:166) ~[metrics-sampler-extension-base.jar:na]
        at org.metricssampler.extensions.base.DefaultSampler.sample(DefaultSampler.java:102) ~[metrics-sampler-extension-base.jar:na]
        at org.metricssampler.resources.SamplerTask.run(SamplerTask.java:40) ~[metrics-sampler-core.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by dimovelev** [comment]
Hi,
thank you very much for the contribution and sorry for the extremely slow response. I will look into your fix over the weekend and will merge your pull request if it works. I intend to start a JVM with JMX credentials turned on and try to fetch data without the fix and with the fix.

Thank you,
Dimo

**Comment by dimovelev** [comment]
Tested and merged the fix. Thank you!
